### ISSUE TITLE
Handle spam email

### ISSUE THREAD

**Issue by davidgatti** [0x4447/0x4447-product-s3-email-lambda-inbound#15]
# Error Symptoms

Spam email won't have a To field. They will have `To: undisclosed-recipients:;`. Because of this the code will crash since there is no email to be seen. 

# Error Message

```
TypeError: Cannot read property 'match' of undefined
at /var/task/index.js:337:8
at new Promise (<anonymous>)
at extract_data (/var/task/index.js:323:9)
at /var/task/index.js:65:11
at <anonymous>
```

# Possible solution

Create a fork that will handle spam emails and good ones.

**Comment by davidgatti** [comment]
Closing as part of org-wide cleanup — no active development planned on this feature. PRs welcome.
